### ISSUE TITLE
How can I add all the files in ~/.ncmpcpp except one?

### ISSUE THREAD

**Issue by joetemp** [jbernard/dotfiles#52]
I would like to 'dotfiles -a ~/.ncmpcpp' but I DO NOT want error.log. I tried adding error.log to the ignore list to no avail. I can't add the individual configs inside ~/.ncmpcpp because they are called 'config' and 'bindings'. That's bound to cause a naming conflict down the road.

Is there a way to rename the files for the purposes of dotfiles? What about nesting them in a directory called 'ncmpcpp' within ~/dotfiles?

At this point, I'm open to anything. Thanks!

**Comment by jbernard** [comment]
Hey Joe, so you have a directory called `~/.ncmpcpp` containing some (but not all) files that you wish to manage in your dotfiles repo?

**Comment by joetemp** [comment]
Yes, that's exactly right. I'd like to add the dir .ncmpcpp but NOT add every single file in it. I've tried adding the files I don't want to the ignore list to no avail. Can I nest them inside a dir called ncmpcpp within ~/dotfiles? BTW, I've already tried this and it didn't work. But I thought I'd ask. Thanks!

**Comment by jbernard** [comment]
This is totally possible, but you'll need to do some manual setup as it's not available through the commandline interface.  The feature you'll need is called `packages`.  Here's how to make this work:

1. Make backups of the files you care about in case something goes wrong and until you've verified that everything is as it should be.

1. In your repository, create a directory (I'm assuming default prefix) called `ncmpcpp`.
1. In your repository, create a file `.dotfilesrc` at the root that contains at least:

   ```
[dotfiles]
packages = [ 'ncmpcpp' ]
```
1. From the real directory `~/.ncmpcpp`, move the files you want in your repository into the directory you created, default would be `~/Dotfiles/ncmpcpp/'.  So now the only files left in the real directory are the one's you don't care to keep synced and the only files in the repository directory are the ones you *do* care to keep synced.

1. Because of the `packages` directive in the config file you created, issuing:
```
dotfiles -s
```
Should create the symlinks correctly and you should be in good shape.  Let me know how it goes.

**Comment by joetemp** [comment]
Worked perfectly. Thanks for your help!
