### ISSUE TITLE
Will we hit 1.0.0 with new API?

### ISSUE THREAD

**Issue by pradyunsg** [jbernard/dotfiles#56]
Will dotfiles be bumped to 1.0.0 once we get the new click API in place?

It makes sense as it a major change and because this library/application/[better-verb-here] is fairly stable as well. It would be nice to have some sort of guarantee that the API will stay the same for that version.

Personally, I'm bootstrapping my dotfiles and I would like to be sure that the version of dotfiles I run has the same interface as I had when writing the bootstrap code.

PS: When should I expect to see the new release? I'm etching to use the new API in the bootstrapping. :smile:

**Comment by jbernard** [comment]
Thanks for asking, the short answer is "yes, definately".  I completely agree that I need make up my mind, settle on an interface, and move on.

Over time a few nice features have been contributed and I'm very grateful for all of the contributions.  With those features and their interaction with others, has come a larger amount of complexity than I'd hoped - and that's really my fault.

I've recently found both some free time and motivation to take a step back and try to see a cleaner implementation and that's what I've been commiting to the `master` branch.  There you will find a new CLI interface (based on Click), which also brings shell completion, colors, and *much* simplier CLI code.
I didn't mean for it to be a rewrite (I know that's annoying) but it's what works for me given my available free time, so that's the approach I've taken.  I've purposely not included anything but the bare minimum features so that I can make sure I get the object model and abstractions correct - before then adding additional features such as configuration files, nested directories/files, prefixes, etc.  It would be great to leave some of those out as less code means less complexity and fewer bugs, I'm hoping that folks that use this program will chime in with what's needed and what's not-so-important.

What's in `master` at the moment supports only flat repositories - where each dotfile is a file (no directories or packages).  If you're curious, I'd love to get your feedback on the progress so far.

My next todo item is to support nested dotfiles and directories (with arbitrary depth instead of 'packages') which I think will both simplify the configuration file and make the application more versitile.

Whatever this current effort ends up becoming, is what will be version 1.0.  I've learned a lot since it started and I think the result will be much better.  Thanks for reading all of this ;)

**Comment by pradyunsg** [comment]
> I'd love to get your feedback on the progress so far.

Sure. If there's anything you want/someone to help out, lemme know. :smile: (goto next comment)

> I didn't mean for it to be a rewrite

It's always painful to do rewrites but the end result is always better, unless rushed. Or so I've been told.

> My next todo item is to support nested dotfiles and directories (with arbitrary depth instead of 'packages')...

Could you make a TODO file so that other's can chip in with their ideas about what coming? And also to act as a roadmap/guide for others.

> Thanks for reading all of this ;)

You're welcome. :wink:

-----

Just a few throwout suggestions & questions:
 - Consider adopting semver from v1.0.0 (http://semver.org/)
   - Worth noting: https://gist.github.com/jashkenas/cbd2b088e20279ae2c8e
 - Are we sticking to ini format or shifting to something else like JSON, YAML or even TOML to the configuration file?
 - I think a 0.7.0 release with all the API/CLI changes should be made followed by a new 1.0.0 release, a few weeks later. This will users a grace period for realizing their dotfiles just got better and easier (to manage).
 - Once 1.0.0 comes out, could the stale branches be trimmed?

PS: I have a feeling that I'm going to bother you a bit with a lot of questions and hopefully, balance it out with help...

**Comment by pradyunsg** [comment]
> you will find a new CLI interface (based on Click), which also brings shell completion, colors, and *much* simplier CLI code

Shoutout to @mitsuhiko
Thanks for an awesome CLI library! :tada:

**Comment by jbernard** [comment]
I'll add a TODO maybe as a file or in the form of a collection of github issues, as soon as I'm confident about the current baseline.

I don't have an affinity to configuration format, once I get to that point I'll take a look and see what seems like the best fit.  Thanks for the suggestions, I didn't know about TOML.

Stale branches will be trimmed, I'll circle back for those pretty soon.

I agree with the semver approach, and a 0.7.0 release will probably be next, certainly not 0.6.x since most things have changed.  I would normally bump the major, except that means 1.0 which carries a few other expectations that I don't want to make right away.  But 1.0.0 will hopefully follow soon after.

**Comment by jbernard** [comment]
Getting really close to the next release, closing this for now.  At the moment there is no configuration file at all, only two env vars for overriding repository path and color options.  I'll probably release with that and see how many people get angry ;)  I need a little time to use it and see if I like the decisions I made, so we'll see.  Will trim the branches and update version shortly

**Comment by pradyunsg** [comment]
Any updates?

**Comment by jbernard** [comment]
Sorry, I got a chance to do some traveling and then life got a little crazy for a bit.  Give me a few days, if I don't get something out by next week I'll owe you a beer (or coffee or tea).

**Comment by pradyunsg** [comment]
Sure thing. No issues. It would be odd if life didn't come in the way. 😛

And, I'm not legally allowed to drink beer yet. 👶

**Comment by pradyunsg** [comment]
You owe me a beer.
