### ISSUE TITLE
Readme is not describing how "master" works?

### ISSUE THREAD

**Issue by niderhoff** [jbernard/dotfiles#80]
In short, I installed from master, because 0.6.4 does not work with python 3.12, but now all the commands have changed. This is very confusing. I wanted to read up how to use this tool now, but the README still describes the old behaviour.

**Comment by jbernard** [comment]
Heya @niderhoff, you're right on both fronts.  I've tagged and released 0.6.5 (which should address the 3.12 compatibility issue) and changed the default branch so that the issue you encountered won't happen again.  Sorry for the delay, and I do appreciate you taking the time to say something about it.
